version: 2
updates:
  - package-ecosystem: "github-actions"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: "npm"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: monthly
    groups:
      astro:
        applies-to: version-updates
        patterns:
          - "@astrojs/*"
          - "astro"
      cloudflare:
        applies-to: version-updates
        patterns:
          - "@cloudflare/*"
          - "wrangler"
      playwright:
        applies-to: version-updates
        patterns:
          - "@axe-core/*"
          - "@playwright/*"
          - "playwright"
      prettier:
        applies-to: version-updates
        patterns:
          - "prettier-*"
          - "prettier"
