version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: monthly
    groups:
      cloudflare:
        applies-to: version-updates
        patterns:
          - "@cloudflare/*"
          - "wrangler"
      parcel:
        applies-to: version-updates
        patterns:
          - "@parcel/*"
          - "parcel"
          - "sharp"
          - "svgo"
      playwright:
        applies-to: version-updates
        patterns:
          - "@axe-core/*"
          - "@playwright/*"
          - "playwright"
    ignore:
      - dependency-name: "sharp"
