name: Auto-fix formatting
on:
  push:
    branches-ignore:
      - trunk
      - dependabot/**
permissions:
  contents: write

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm ci
      - run: npx prettier --write .
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git add .
      - run: git commit -m "Format with Prettier"
        continue-on-error: true
      - run: git push
