name: Run tests

on: push

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - run: npm ci

      - run: npm run prettier:check

      - run: npm run type-check

      - run: npm run build

  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Cache playwright binaries
        uses: actions/cache@v4
        with:
          key: playwright-${{ hashFiles('package-lock.json') }}
          path: ~/.cache/ms-playwright

      - run: npm ci

      - name: Install Playwright dependencies
        run: npx playwright install --with-deps chromium

      - run: npm run test
